# spring
spring:
  application:
    name: dubbo-service-search
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
# elasticsearch

# log
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level) %clr(${PID:-}){magenta} %clr([%t]){faint} %clr([%F:%L]){cyan} %clr(:){faint} %m%n%throwable'
# index
