# spring
spring:
  application:
    name: &application_name dubbo-api-admin
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  messages:
    basename: i18n.message
  web:
    resources:
      cache:
        use-last-modified: true
        cache control:
          max-age: 3600s
  threads:
    virtual:
      enabled: true
#server
server:
  port: 7071
  servlet:
    context-path: /admin
  tomcat:
    accept-count: 10
    threads:
      max: 10
      min-spare: 5
  error:
    path: /liyz/error
  shutdown: graceful
# log
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level) %clr(${PID:-}){magenta} %clr([%t]){faint} %clr([%F:%L]){cyan} %clr(:){faint} %m%n%throwable'
# dubbo
dubbo:
  application:
    name: *application_name
    qos-enable: false
    serialize-check-status: WARN
  protocol:
    port: 20771
    threads: 1
  provider:
    filter: remoteServiceExceptionFilter,-exception
    version: 1.0.0
    group: *application_name
  consumer:
    version: 1.0.0
    check: false
    cluster: failfast
    timeout: 60000
  registry:
    timeout: 5000
    address: nacos://localhost:8848?namespace=liyz
  metadata-report:
    address: nacos://localhost:8848?namespace=liyz
# springdoc
springdoc:
  default-flat-param-object: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: test
      display-name: 测试
      paths-to-match:
        - /**
      packages-to-scan:
        - com.liyz.boot3.api.admin.controller.test
    - group: authentication
      display-name: 鉴权
      paths-to-match:
        - /**
      packages-to-scan:
        - com.liyz.boot3.api.admin.controller.authentication
    - group: staff
      display-name: 员工
      paths-to-match:
        - /**
      packages-to-scan:
        - com.liyz.boot3.api.admin.controller.staff
    - group: search
      display-name: 搜索
      paths-to-match:
        - /**
      packages-to-scan:
        - com.liyz.boot3.api.admin.controller.search
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  basic:
    username: abc
    password: 123
    enable: false
auth:
  advice:
    enable: true