#server
server:
  port: 8080
  shutdown: graceful
#spring
spring:
  application:
    name: &application_name dubbo-gateway
  #gateway-#路由规则
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: api-admin
          uri: http://localhost:7071
          predicates:
            - Path=/admin/**
        - id: api-user
          uri: http://localhost:7072
          predicates:
            - Path=/user/**
# dubbo
dubbo:
  application:
    name: *application_name
    qos-enable: false
    serialize-check-status: WARN
  protocol:
    port: 20774
    threads: 2
  provider:
    filter: remoteServiceExceptionFilter,-exception
    version: 1.0.0
  consumer:
    version: 1.0.0
    check: false
    cluster: failfast
    timeout: 60000
  registry:
    timeout: 5000
    address: nacos://localhost:8848
  metadata-report:
    address: nacos://localhost:8848
knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    routes:
      - name: 后台管理服务
        url: /admin/v3/api-docs?group=default
        service-name: api-admin
        context-path: /admin
        order: 1
      - name: 后台管理服务-鉴权
        url: /admin/v3/api-docs/authentication?group=default
        service-name: api-admin
        context-path: /admin
        order: 2
      - name: 后台管理服务-测试
        url: /admin/v3/api-docs/test?group=default
        service-name: api-admin
        context-path: /admin
        order: 3
      - name: 后台管理服务-搜索
        url: /admin/v3/api-docs/search?group=default
        service-name: api-admin
        context-path: /admin
        order: 4
      - name: 用户前台服务
        url: /user/v3/api-docs?group=default
        service-name: api-user
        context-path: /user
        order: 101
      - name: 用户前台服务-测试
        url: /user/v3/api-docs/test?group=default
        service-name: api-user
        context-path: /user
        order: 102
      - name: 用户前台服务-搜索
        url: /user/v3/api-docs/search?group=default
        service-name: api-user
        context-path: /user
        order: 103
anonymous:
  mapping:
    server:
      dubbo-api-admin:
        - /auth/register
        - /auth/login
        - /test/hello
      dubbo-api-user:
        - /auth/register
        - /auth/login
# 免鉴权