server:
  shutdown: graceful
  port: 7070
  error:
    path: /liyz/error
# spring
spring:
  application:
    name: &application_name dubbo-service-auth
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 60s
  boot:
    admin:
      client:
        url: http://127.0.0.1:7060
# datasource
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
# hikari
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  messages:
    basename: i18n.message
  # cache
  cache:
    cache-names: test,bug
    type: redis
    redis:
      time-to-live: 300000
      key-prefix: 'auth:'
      cache-null-values: true
      enable-statistics: true
      use-key-prefix: true
# redis
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
# log
logging:
  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level) %clr(${PID:-}){magenta} %clr([%t]){faint} %clr([%F:%L]){cyan} %clr(:){faint} %m%n%throwable'
  level:
    com.liyz.boot3.service.auth.dao: debug
    org.apache.dubbo.spring.security.jackson.ObjectMapperCodec: error
  file:
    path: \srv\logs\${spring.application.name}\${spring.application.name}.log
# dubbo
dubbo:
  application:
    name: *application_name
    qos-enable: false
    serialize-check-status: STRICT
  protocol:
    port: 20770
    threads: 200
  provider:
    filter: remoteServiceExceptionFilter,-exception
    version: 1.0.0
    group: auth
  consumer:
    version: 1.0.0
    check: false
    cluster: failfast
    timeout: 60000
  registry:
    timeout: 5000
    address: nacos://localhost:8848?namespace=liyz
  metadata-report:
    address: nacos://localhost:8848?namespace=liyz
  scan:
    base-packages: com.liyz.boot3.service.auth.provider
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always